import re
import logging
from typing import List, Dict, Any, Optional, Tuple, Set
from app.schemas.chat import CitationItem
from app.services.context_builder import EvidenceChunk

logger = logging.getLogger(__name__)


class CitationEngine:
    """
    Validates, filters, and enriches citations generated by the LLM.
    Guarantees that no hallucinated or nonexistent citation IDs are returned to the user.
    """

    def __init__(self):
        # Regex to detect bracket citations like [1], [2], [1, 2], [1][2]
        self.bracket_pattern = re.compile(r"\[(\d+)\]")

    def extract_citation_ids_from_text(self, text: str) -> List[int]:
        """Extract all integer citation IDs present in bracket tags e.g. [1], [2]."""
        matches = self.bracket_pattern.findall(text)
        ids = []
        for m in matches:
            try:
                ids.append(int(m))
            except ValueError:
                continue
        return ids

    def validate_and_enrich(
        self,
        raw_answer: str,
        raw_citations: Optional[List[Dict[str, Any]]],
        evidence_chunks: List[EvidenceChunk],
    ) -> Tuple[str, List[CitationItem], List[Dict[str, Any]]]:
        """
        Validates citation IDs against actual available evidence chunks.
        
        Returns:
            - sanitized_answer: Cleaned answer with invalid citation markers removed
            - validated_citations: List of enriched CitationItem objects
            - rejected_citations: List of rejected/hallucinated citation attempts for observability
        """
        # Map available evidence IDs to their actual metadata
        evidence_map: Dict[int, EvidenceChunk] = {
            chunk.id: chunk for chunk in evidence_chunks
        }

        validated_citations: List[CitationItem] = []
        rejected_citations: List[Dict[str, Any]] = []
        seen_ids: Set[int] = set()
        seen_rejected_ids: Set[int] = set()

        # 1. Process structured citations returned by LLM JSON
        if raw_citations:
            for item in raw_citations:
                try:
                    c_id = int(item.get("id", 0))
                    reason = item.get("reason", "")
                except (ValueError, TypeError):
                    rejected_citations.append({"item": item, "reason": "Malformed ID"})
                    continue

                if c_id in evidence_map:
                    if c_id not in seen_ids:
                        ev = evidence_map[c_id]
                        validated_citations.append(
                            CitationItem(
                                id=ev.id,
                                standard_number=ev.standard_number,
                                title=ev.title,
                                clause=ev.clause,
                                page=ev.page_start,
                                source=ev.source,
                                snippet=ev.text[:250] + ("..." if len(ev.text) > 250 else ""),
                                score=ev.score,
                                reason=reason,
                            )
                        )
                        seen_ids.add(c_id)
                else:
                    logger.warning(f"Rejected hallucinated citation ID [{c_id}] not in evidence")
                    if c_id not in seen_rejected_ids:
                        rejected_citations.append(
                            {"id": c_id, "reason": "ID not found in retrieved evidence chunks"}
                        )
                        seen_rejected_ids.add(c_id)

        # 2. Extract citations directly embedded in the text if not captured in structured output
        text_ids = self.extract_citation_ids_from_text(raw_answer)
        for t_id in text_ids:
            if t_id in evidence_map and t_id not in seen_ids:
                ev = evidence_map[t_id]
                validated_citations.append(
                    CitationItem(
                        id=ev.id,
                        standard_number=ev.standard_number,
                        title=ev.title,
                        clause=ev.clause,
                        page=ev.page_start,
                        source=ev.source,
                        snippet=ev.text[:250] + ("..." if len(ev.text) > 250 else ""),
                        score=ev.score,
                        reason="Referenced in text body",
                    )
                )
                seen_ids.add(t_id)
            elif t_id not in evidence_map and t_id not in seen_rejected_ids:
                rejected_citations.append(
                    {"id": t_id, "reason": "In-text bracket ID not in retrieved evidence"}
                )
                seen_rejected_ids.add(t_id)


        # 3. If no specific citations were referenced by the model, but high-confidence evidence was used,
        # attach the top evidence chunk as an overarching reference
        if not validated_citations and evidence_chunks:
            top_ev = evidence_chunks[0]
            validated_citations.append(
                CitationItem(
                    id=top_ev.id,
                    standard_number=top_ev.standard_number,
                    title=top_ev.title,
                    clause=top_ev.clause,
                    page=top_ev.page_start,
                    source=top_ev.source,
                    snippet=top_ev.text[:250] + ("..." if len(top_ev.text) > 250 else ""),
                    score=top_ev.score,
                    reason="Primary retrieved source grounding this topic",
                )
            )

        # 4. Remove hallucinated in-text bracket tags that were rejected
        sanitized_answer = raw_answer
        for rej in rejected_citations:
            rej_id = rej.get("id")
            if rej_id:
                sanitized_answer = re.sub(rf"\[{rej_id}\]", "", sanitized_answer)

        # Sort validated citations by ID
        validated_citations.sort(key=lambda x: x.id)

        return sanitized_answer.strip(), validated_citations, rejected_citations
