import uuid
from typing import List, Optional, Any, Dict
from pydantic import BaseModel, Field


class ChatMessageInput(BaseModel):
    """A past conversation turn provided as context."""
    role: str = Field(..., description="Role of message author: 'user' or 'assistant'")
    content: str = Field(..., description="Message text content")


class ChatRequest(BaseModel):
    """Incoming user chat request to e-BIS Sahayak Groq AI Assistant."""
    message: str = Field(..., min_length=1, max_length=1000, description="User question or query")
    conversation_id: Optional[uuid.UUID] = Field(None, description="Optional conversation session ID")
    history: Optional[List[ChatMessageInput]] = Field(default=[], description="Recent conversation turns")
    language: Optional[str] = Field("auto", description="Language preference: 'auto', 'en', 'hi', or 'ta'")


class SourceItem(BaseModel):
    """Authoritative source metadata with explicit data provenance and claim traceability."""
    title: Optional[str] = Field(None, description="Title or name of official document or portal")
    url: Optional[str] = Field(None, description="Official portal URL")
    source_type: Optional[str] = Field("official_bis", description="Category of source")
    authority: Optional[str] = Field("Bureau of Indian Standards", description="Issuing authority or body")
    verified: Optional[bool] = Field(True, description="True if provenance is established from official source")
    verification_status: Optional[str] = Field("authoritative_curated", description="'authoritative_verified', 'authoritative_curated', 'limited', 'unverified', 'procedure_guided'")
    provenance: Optional[str] = Field(None, description="Source gazette notification or catalogue origin")
    last_verified: Optional[str] = Field("2026-01-15", description="Last verified date string")
    source_priority: Optional[int] = Field(1, description="Source priority order (1=official_bis, 2=official_gov, 3=registered_lab, 4=other)")
    evidence_scope: Optional[str] = Field(None, description="Granular scope of supported evidence")
    supported_claims: List[str] = Field(default=["standard_existence"], description="Specific claim types supported by evidence")


CitationItem = SourceItem


class ChatResponse(BaseModel):
    """Normalized Groq AI Assistant API Response."""
    answer: str = Field(..., description="Response message generated by Groq AI Assistant")
    intent: str = Field("ASSISTANT_CAPABILITY", description="Classified user intent")
    response_type: str = Field(
        "DIRECT_RESPONSE",
        description="Explicit response category: 'DIRECT_RESPONSE', 'CLARIFICATION_REQUIRED', 'PRODUCT_APPLICABILITY', 'STANDARD_INFORMATION', 'CERTIFICATION_INFORMATION', 'OUT_OF_SCOPE', 'ERROR'"
    )
    grounded: bool = Field(False, description="True only when response is supported by explicitly provided source content")
    evidence_status: Optional[str] = Field("strong", description="Quality of supporting evidence: 'strong', 'limited', 'insufficient'")
    warnings: List[str] = Field(default=[], description="Regulatory or evidence caveats")
    needs_clarification: bool = Field(False, description="True if query is underspecified")
    clarification_question: Optional[str] = Field(None, description="Specific clarification prompt if required")
    sources: List[SourceItem] = Field(default=[], description="Source items if supplied")
    citations: List[SourceItem] = Field(default=[], description="Citations list for API compatibility")
    sources_used: int = Field(0, description="Count of sources used")
    insufficient_evidence: bool = Field(False, description="True if specific regulatory facts require external verification")
    clarification_needed: bool = Field(False, description="True if query requires product or category clarification")
    clarification_options: List[str] = Field(default=[], description="Clarification options for user selection")
    retrieval_triggered: bool = Field(False, description="True when evidence retrieval pipeline is executed")
    conversation_id: Optional[uuid.UUID] = Field(None, description="Conversation session ID")
    model: str = Field("llama-3.3-70b-versatile", description="Groq model identifier")
    processing_time_ms: float = Field(0.0, description="Processing latency in milliseconds")
    language: str = Field("en", description="Detected or generated response language ('en', 'hi', 'ta')")
    confidence: Optional[float] = Field(None, description="Always null in Groq-only mode (no fake confidence scores)")


class ChatDebugResponse(BaseModel):
    """Developer / Tester observability response for Groq AI Assistant."""
    request_query: str
    normalized_query: str
    intent: str
    response_type: str
    system_prompt: str
    assembled_messages: List[Dict[str, str]]
    raw_llm_response: str
    final_answer: str
    model: str
    timing_ms: float
